
--# CREATE A DATABASE

CREATE DATABASE [mssqltogcp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'mssqltogcp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\mssqltogcp.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'mssqltogcp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\mssqltogcp_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [mssqltogcp] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [mssqltogcp] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [mssqltogcp] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [mssqltogcp] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [mssqltogcp] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [mssqltogcp] SET ARITHABORT OFF 
GO
ALTER DATABASE [mssqltogcp] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [mssqltogcp] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [mssqltogcp] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [mssqltogcp] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [mssqltogcp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [mssqltogcp] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [mssqltogcp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [mssqltogcp] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [mssqltogcp] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [mssqltogcp] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [mssqltogcp] SET  DISABLE_BROKER 
GO
ALTER DATABASE [mssqltogcp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [mssqltogcp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [mssqltogcp] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [mssqltogcp] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [mssqltogcp] SET  READ_WRITE 
GO
ALTER DATABASE [mssqltogcp] SET RECOVERY FULL 
GO
ALTER DATABASE [mssqltogcp] SET  MULTI_USER 
GO
ALTER DATABASE [mssqltogcp] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [mssqltogcp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [mssqltogcp] SET DELAYED_DURABILITY = DISABLED 
GO
USE [mssqltogcp]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [mssqltogcp]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [mssqltogcp] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
--# CREATE AND POPULATE A TABLE 
USE [mssqltogcp]
FO
CREATE TABLE testtable 
(
	ID INT NOT NULL,
	[Text] NCHAR(100) NULL
)

INSERT INTO testtable VALUES (1, 'this is data from a sql server database')

--# CREATE A SQL LOGIN 
USE [master]
GO
CREATE LOGIN [gcp] WITH PASSWORD=N'password', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [gcp]
GO
use [mssqltogcp];
GO
use [master];
GO
USE [mssqltogcp]
GO
CREATE USER [gcp] FOR LOGIN [gcp]
GO
USE [mssqltogcp]
GO
ALTER ROLE [db_datareader] ADD MEMBER [gcp]
GO


--# SET MIXED AUTHENTICATION MODE ON THE SQL SERVER 

USE [master]
GO
EXEC xp_instance_regwrite N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'LoginMode', REG_DWORD, 2
GO


-- AT THIS POINT, RESTART THE SQL SERVER
